config/routes.rb
CapitalAdmin::Application.routes.draw do
  resources :typemodes

  root :to => 'application#index' 
  
  resources :regions
  match 'regions/new' => 'regions#new'
  
  match 'parser' => 'parser#index'
  match 'map' => 'map#index'
  match 'content' => 'content#index'

  match 'parser/go' => 'parser#go'
  match 'parser/preload' => 'parser#preload'
  match 'map/load' => 'map#load'
  match 'map/viewer/json/path' => 'map#get_regions'
  match 'map/viewer/json/pavilion_by_path' => 'map#get_pavilion_by_path'
  match 'map/viewer' => 'map#viewer'
  match 'map/viewer/set_attr' => 'map#set_attr'
  match 'map/viewer/delete_path' => 'map#delete_path'

  
  mount API::API => '/'

end

app/models/typemode.rb
class Typemode < ActiveRecord::Base
	belongs_to :store
 	attr_accessible :title, :image, :store_id, :path
 	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/typemodes_controller.rb
class TypemodesController < ApplicationController
  # GET /typemodes
  # GET /typemodes.json
  def index
    @typemodes = Typemode.order("store_id").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @typemodes }
    end
  end

  # GET /typemodes/1
  # GET /typemodes/1.json
  def show
    @typemode = Typemode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @typemode }
    end
  end

  # GET /typemodes/new
  # GET /typemodes/new.json
  def new
    @typemode = Typemode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @typemode }
    end
  end

  # GET /typemodes/1/edit
  def edit
    @typemode = Typemode.find(params[:id])
  end

  # POST /typemodes
  # POST /typemodes.json
  def create
    @typemode = Typemode.new(params[:typemode])

    respond_to do |format|
      if @typemode.save
        format.html { redirect_to @typemode, notice: 'Typemode was successfully created.' }
        format.json { render json: @typemode, status: :created, location: @typemode }
      else
        format.html { render action: "new" }
        format.json { render json: @typemode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /typemodes/1
  # PUT /typemodes/1.json
  def update
    @typemode = Typemode.find(params[:id])

    respond_to do |format|
      if @typemode.update_attributes(params[:typemode])
        format.html { redirect_to @typemode, notice: 'Typemode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @typemode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /typemodes/1
  # DELETE /typemodes/1.json
  def destroy
    @typemode = Typemode.find(params[:id])
    @typemode.destroy

    respond_to do |format|
      format.html { redirect_to typemodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/typemodes_helper.rb
module TypemodesHelper
end

app/views/typemodes/_form.html.haml
= form_for @typemode, :html => { :multipart => true } do |f|
  - if @typemode.errors.any?
    #error_explanation
      %h2= "#{pluralize(@typemode.errors.count, "error")} prohibited this typemode from being saved:"
      %ul
        - @typemode.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :store
    = f.collection_select(:store_id, Store.all, :id, :title, :prompt => true)
  .field
    = f.file_field :image
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :path
    = f.text_area :path
  .actions
    = f.submit 'Save'

app/views/typemodes/edit.html.haml
%h1 Editing typemode

= render 'form'

= link_to 'Show', @typemode
\|
= link_to 'Back', typemodes_path

app/views/typemodes/index.html.haml
%h1 Listing typemodes

%table
  %tr
    %th Title
    %th
    %th
    %th

  - @typemodes.each do |typemode|
    %tr
      %td= typemode.title
      %td= !typemode.store.nil? ? typemode.store.title : "Not avalible"
      %td= link_to 'Show', typemode
      %td= link_to 'Edit', edit_typemode_path(typemode)
      %td= link_to 'Destroy', typemode, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Typemode', new_typemode_path

app/views/typemodes/new.html.haml
%h1 New typemode

= render 'form'

= link_to 'Back', typemodes_path

app/views/typemodes/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @typemode.title

= link_to 'Edit', edit_typemode_path(@typemode)
\|
= link_to 'Back', typemodes_path