config/routes.rb
CapitalAdmin::Application.routes.draw do
  resources :typemodes

  root :to => 'application#index' 
  
  resources :regions
  match 'regions/new' => 'regions#new'
  
  match 'parser' => 'parser#index'
  match 'map' => 'map#index'
  match 'content' => 'content#index'

  match 'parser/go' => 'parser#go'
  match 'parser/preload' => 'parser#preload'
  match 'map/load' => 'map#load'
  match 'map/viewer/json/path' => 'map#get_regions'
  match 'map/viewer/json/pavilion_by_path' => 'map#get_pavilion_by_path'
  match 'map/viewer' => 'map#viewer'
  match 'map/viewer/set_attr' => 'map#set_attr'
  match 'map/viewer/delete_path' => 'map#delete_path'

  
  mount API::API => '/'

end

app/models/region.rb
class Region < ActiveRecord::Base
	# self.inheritance_column = nil

  	belongs_to :pavilion
  	belongs_to :store
  	attr_accessible :pavilion_id, :store_id, :path, :floor, :color, :titlebox, :typemode
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  # GET /regions
  # GET /regions.json
  def index
    @regions = Store.find(params[:store]).regions

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @regions }
    end
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
    @region = Store.find(params[:store]).regions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @region }
    end
  end

  # GET /regions/new
  # GET /regions/new.json
  def new
    @region = Region.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @region }
    end
  end

  # GET /regions/1/edit
  def edit
    @region = Region.find(params[:id])
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(params[:region])

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render json: @region, status: :created, location: @region }
      else
        format.html { render action: "new" }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /regions/1
  # PUT /regions/1.json
  def update
    @region = Region.find(params[:id])

    respond_to do |format|
      if @region.update_attributes(params[:region])
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region = Region.find(params[:id])
    @region.destroy

    respond_to do |format|
      format.html { redirect_to regions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.haml
= form_for @region do |f|
  - if @region.errors.any?
    #error_explanation
      %h2= "#{pluralize(@region.errors.count, "error")} prohibited this region from being saved:"
      %ul
        - @region.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :store
    = f.collection_select(:store_id, Store.find(:all), :id, :title, :prompt => true, :selected => params[:store])
  .field
    = f.label :path
    = f.text_field :path
  .field
    = f.label :pavilion
    = f.collection_select(:pavilion_id, Store.find(params[:store]).pavilions, :id, :brandname, :prompt => true)
  .actions
    = f.submit 'Save'

app/views/regions/edit.html.haml
%h1 Editing region

= render 'form'

= link_to 'Show', @region
\|
= link_to 'Back', regions_path

app/views/regions/index.html.haml
%h1 Listing regions

%table
  %tr
    %th Path
    %th Pavilion
    %th
    %th
    %th

  - @regions.each do |region|
    %tr
      %td= region.path
      %td= region.pavilion.brandname
      %td= link_to 'Show', region
      %td= link_to 'Edit', edit_region_path(region)
      %td= link_to 'Destroy', region, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/regions/new.html.haml
%h1 New region

= render 'form'

= link_to 'Back', regions_path, :store => params[:store]

app/views/regions/show.html.haml
%p#notice= notice

%p
  %b Path:
  = @region.path
%p
  %b Pavilion:
  = @region.pavilion.brandname

= link_to 'Edit', edit_region_path(@region)
\|
= link_to 'Back', regions_path, :store => params[:store]